import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import { ClientLayoutWrapper } from "@/components/Wrapper/ClientLayoutWrapper";
import ReduxProvider from "@/provider/ReduxProvider";
import ScrollToTop from "@/components/common/ScrollToTop";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Campus Gigs",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ToastContainer style={{ zIndex: 999999999 }} />
        <ScrollToTop />
        <ReduxProvider>
          <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
